### ISSUE TITLE
 zookeeper1: chmod: cannot access `/vagrant/scripts/*.sh': No such file or directory

### ISSUE THREAD

**Issue by MartinKuhne** [eucuepo/vagrant-kafka#21]
Ran into this on Windows (two different machines). This one is 1809.

```
    zookeeper1: Installed:
    zookeeper1:   java-1.8.0-openjdk-devel.x86_64 1:1.8.0.222.b10-0.el6_10
    zookeeper1:
    zookeeper1: Dependency Installed:
    zookeeper1:   atk.x86_64 0:1.30.0-1.el6
[…]
    zookeeper1:   xorg-x11-fonts-Type1.noarch 0:7.2-11.el6
    zookeeper1:
    zookeeper1: Complete!
    zookeeper1: kafka_2.11-1.1.0/
    zookeeper1: kafka_2.11-1.1.0/LICENSE
    zookeeper1: kafka_2.11-1.1.0/NOTICE
    zookeeper1: kafka_2.11-1.1.0/bin/
    zookeeper1: kafka_2.11-1.1.0/bin/connect-distributed.sh
    zookeeper1: kafka_2.11-1.1.0/bin/connect-standalone.sh
    zookeeper1: kafka_2.11-1.1.0/bin/kafka-acls.sh
    zookeeper1: kafka_2.11-1.1.0/bin/kafka-broker-api-versions.sh
    zookeeper1: kafka_2.11-1.1.0/bin/kafka-configs.sh
[…]
    zookeeper1: kafka_2.11-1.1.0/libs/kafka-streams-examples-1.1.0.jar
    zookeeper1: done installing JDK and Kafka...
    zookeeper1: chmod: cannot access `/vagrant/scripts/*.sh': No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
C:\oss\vagrant-kafka>
```
